# First Draft Codes for Machine Learning Project

## Import Libraries

In [26]:
# Import libraries necessary for this project
import numpy as np
import pandas as pd
from time import time
import matplotlib.pyplot as plt
%matplotlib inline 
import visuals as vs

## Read csv Data Files

In [2]:
def readCSV():
    raw_data = pd.read_csv('raw_data.csv')
    return raw_data
raw_data = readCSV()
raw_data.head()

Date        Unix Ticker      Price  stock_p_change      SP500  \
0   1/30/04 19:01  1075460462      a  22.984629          -41.37  84.478371   
1    4/13/04 4:07  1081800431      a  19.336773          -32.89  84.572807   
2  12/13/04 21:37  1102945054      a  14.865800           50.92  90.894150   
3    1/22/05 5:17  1106342239      a  13.593730           57.11  88.599785   
4     1/9/06 2:35  1136745316      a  21.544186            4.47  99.419518   

   SP500_p_change    Market Cap  Enterprise Value  Trailing P/E  ...    \
0            5.46  1.745000e+10      1.652000e+10           NaN  ...     
1            5.64  1.532000e+10      1.477000e+10           NaN  ...     
2            7.57  1.161000e+10      1.037000e+10         33.58  ...     
3            9.77  1.071000e+10      9.760000e+09         30.70  ...     
4           11.58  1.712000e+10      1.487000e+10         52.82  ...     

   Avg Vol (3 month)  Shares Outstanding        Float  % Held by Insiders  \
0          2989323.0         476150000.0  428500000.0               10.01   
1          3536636.0         480750000.0  432700000.0               10.00   
2          2780227.0         487000000.0  389600000.0               20.00   
3          2459863.0         491070000.0  441400000.0               10.12   
4          3843670.0         494180000.0          NaN                0.57   

   % Held by Institutions  Shares Short (as of  Short Ratio  Short % of Float  \
0                   63.03            9300000.0        3.923              2.17   
1                   66.79            7520000.0        2.328              1.74   
2                   66.68            6930000.0        2.638              1.78   
3                   67.08            7040000.0        2.385              1.60   
4                   70.40           10980000.0        2.300              2.20   

   Shares Short (prior month  Label  
0                  6930000.0    Yes  
1                  9170000.0    Yes  
2                  6540000.0    Yes  
3                  6930000.0    Yes  
4                  5840000.0    Yes  

[5 rows x 49 columns]

## Chose features in the data

In [3]:
columns_names = list(raw_data)
columns_names

['Date',
 'Unix',
 'Ticker',
 'Price',
 'stock_p_change',
 'SP500',
 'SP500_p_change',
 'Market Cap',
 'Enterprise Value',
 'Trailing P/E',
 'Forward P/E',
 'PEG Ratio',
 'Price/Sales',
 'Price/Book',
 'Enterprise Value/Revenue',
 'Enterprise Value/EBITDA',
 'Profit Margin',
 'Operating Margin',
 'Return on Assets',
 'Return on Equity',
 'Revenue',
 'Revenue Per Share',
 'Qtrly Revenue Growth',
 'Gross Profit',
 'EBITDA',
 'Net Income Avl to Common',
 'Diluted EPS',
 'Qtrly Earnings Growth',
 'Total Cash',
 'Total Cash Per Share',
 'Total Debt',
 'Total Debt/Equity',
 'Current Ratio',
 'Book Value Per Share',
 'Operating Cash Flow',
 'Levered Free Cash Flow',
 'Beta',
 '50-Day Moving Average',
 '200-Day Moving Average',
 'Avg Vol (3 month)',
 'Shares Outstanding',
 'Float',
 '% Held by Insiders',
 '% Held by Institutions',
 'Shares Short (as of',
 'Short Ratio',
 'Short % of Float',
 'Shares Short (prior month',
 'Label']

In [44]:
def chose_features():
    features = [
 'Trailing P/E',
 'Forward P/E',
 'PEG Ratio',
 'Price/Sales',
 'Price/Book',
 'Enterprise Value/Revenue',
 'Enterprise Value/EBITDA',
 'Profit Margin',
 'Operating Margin',
 'Return on Assets',
 'Return on Equity',
 'Revenue Per Share',
 'Qtrly Revenue Growth', 'EBITDA',
 'Net Income Avl to Common',
 'Diluted EPS',
 'Qtrly Earnings Growth',
 'Total Cash',
 'Total Cash Per Share',
 'Total Debt',
 'Total Debt/Equity',
 'Current Ratio',
 'Book Value Per Share',
 'Operating Cash Flow',
 'Levered Free Cash Flow',
 'Beta',
 '50-Day Moving Average',
 '200-Day Moving Average',
 'Avg Vol (3 month)',
 'Shares Outstanding',
 '% Held by Insiders',
 '% Held by Institutions',
 'Shares Short (as of',
 'Short Ratio',
 'Short % of Float','Label']
    selected_columns_data = raw_data[features]
    return features,selected_columns_data
features,selected_columns_data = chose_features()
selected_columns_data.head()

Trailing P/E  Forward P/E  PEG Ratio  Price/Sales  Price/Book  \
0           NaN        25.83       3.84         2.80        6.01   
1           NaN        20.83       2.89         2.43        4.98   
2         33.58        15.79       1.62         1.61        3.24   
3         30.70        14.34       1.51         1.52        3.04   
4         52.82        19.69       1.81         3.31        4.26   

   Enterprise Value/Revenue  Enterprise Value/EBITDA  Profit Margin  \
0                      2.73                      NaN         -29.56   
1                      2.35                      NaN         -25.56   
2                      1.44                   15.300           4.86   
3                      1.36                   14.400           4.86   
4                      2.89                   35.665           6.38   

   Operating Margin  Return on Assets  ...    50-Day Moving Average  \
0            -11.97            -24.95  ...                    29.47   
1             -6.20            -23.59  ...                    33.53   
2              5.38              5.26  ...                    23.64   
3              5.38              5.26  ...                    23.71   
4              3.58              1.68  ...                    34.92   

   200-Day Moving Average  Avg Vol (3 month)  Shares Outstanding  \
0                   23.24          2989323.0         476150000.0   
1                   27.32          3536636.0         480750000.0   
2                   25.64          2780227.0         487000000.0   
3                   24.72          2459863.0         491070000.0   
4                   30.86          3843670.0         494180000.0   

   % Held by Insiders  % Held by Institutions  Shares Short (as of  \
0               10.01                   63.03            9300000.0   
1               10.00                   66.79            7520000.0   
2               20.00                   66.68            6930000.0   
3               10.12                   67.08            7040000.0   
4                0.57                   70.40           10980000.0   

   Short Ratio  Short % of Float  Label  
0        3.923              2.17    Yes  
1        2.328              1.74    Yes  
2        2.638              1.78    Yes  
3        2.385              1.60    Yes  
4        2.300              2.20    Yes  

[5 rows x 36 columns]

# Preprocessing

## Handle *Missing Data*

In [48]:
# selected_columns_data.isna()
selected_columns_data = selected_columns_data.dropna()

### Define Y matrix as the outperformers

In [120]:
Y = selected_columns_data[features[-1]].values
# Encode the label for score calculating later
from sklearn.preprocessing import LabelBinarizer
lb = LabelBinarizer()
Y = np.array([number[0] for number in lb.fit_transform(Y)])
Y

array([0, 1, 1, ..., 1, 1, 1])

### Define X matrixes

In [91]:
X = np.matrix(selected_columns_data[features[0:-1]].values)
X

matrix([[  5.08000000e+00,   1.73000000e+01,   1.26000000e+00, ...,
           6.92000000e+06,   3.40000000e+00,   1.60000000e+00],
        [  4.63000000e+00,   1.70100000e+01,   1.21000000e+00, ...,
           7.35000000e+06,   2.50000000e+00,   1.80000000e+00],
        [  4.33000000e+00,   1.51100000e+01,   1.13000000e+00, ...,
           5.91000000e+06,   2.80000000e+00,   1.50000000e+00],
        ..., 
        [  1.74800000e+01,   1.38600000e+01,   1.27000000e+00, ...,
           4.30000000e+06,   2.90000000e+00,   2.70000000e+00],
        [  1.75100000e+01,   1.38900000e+01,   1.29000000e+00, ...,
           4.52000000e+06,   2.80000000e+00,   2.90000000e+00],
        [  1.66200000e+01,   1.39600000e+01,   1.34000000e+00, ...,
           5.67000000e+06,   3.90000000e+00,   4.10000000e+00]])

## Train Test Split

In [112]:
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test = train_test_split(X,Y,test_size = 0.2)
X_train

matrix([[  1.64600000e+01,   1.35400000e+01,   1.23000000e+00, ...,
           1.26000000e+06,   1.80000000e+00,   1.30000000e+00],
        [  1.49470000e+02,   2.98100000e+01,   1.13000000e+00, ...,
           9.20000000e+06,   2.20000000e+00,   5.90000000e+00],
        [  1.65300000e+01,   2.25400000e+01,   1.73000000e+00, ...,
           6.26000000e+06,   3.00000000e+00,   1.10000000e+00],
        ..., 
        [  5.82000000e+00,   1.56400000e+01,   7.20000000e-01, ...,
           2.02800000e+07,   2.60000000e+00,   9.20000000e+00],
        [  4.08400000e+01,   3.24600000e+01,   3.72000000e+00, ...,
           5.67100000e+07,   6.60000000e+00,   4.20000000e+00],
        [  1.60600000e+01,   1.38500000e+01,   1.05000000e+00, ...,
           4.06500000e+07,   1.40000000e+00,   2.90000000e+00]])

## Data Report

In [99]:
def data_report(df):
    no_good_df = df.loc[df['Label'] == 'No']
    good_df = df.loc[df['Label'] == 'Yes']
    print("Number of outperformered stocks: {}".format(len(good_df)))
    print("Number of underperformered stocks: {}".format(len(no_good_df)))
    print("Total number of data points: {}".format(len(df)))
    print("Percentage of outperformer stocks: {}".format(len(no_good_df)/len(good_df)))
    print('----------------------------------------------------------------------------')
    print("Train Sample Size: {}".format(len(X_train)))
    print("Test Sample Size: {}".format(len(X_test)))
data_report(selected_columns_data)
# data_report(raw_data)

Number of outperformered stocks: 1505
Number of underperformered stocks: 303
Total number of data points: 1808
Percentage of outperformer stocks: 0.20132890365448505
----------------------------------------------------------------------------
Train Sample Size: 1446
Test Sample Size: 362


## Data Normalization

### *MinMax Scaler*

In [100]:
def minmax_scale(X):
    from sklearn.preprocessing import MinMaxScaler
    scaler = MinMaxScaler()
    X = scaler.fit_transform(X)
    return X
X_train,X_test = minmax_scale(X_train),minmax_scale(X_test)
X_train

array([[  2.26501347e-02,   2.70194986e-01,   3.36953771e-01, ...,
          2.45820571e-01,   2.38461538e-01,   8.83002208e-02],
       [  8.81540485e-03,   1.33530641e-01,   3.37936740e-01, ...,
          4.51136422e-02,   2.23076923e-01,   7.72626932e-02],
       [  6.68477605e-03,   9.22701950e-02,   3.34102190e-01, ...,
          2.39490180e-03,   1.15384615e-02,   1.10375276e-02],
       ..., 
       [  6.72497660e-03,   9.75800836e-02,   3.34277372e-01, ...,
          3.73840673e-02,   1.96153846e-01,   1.89845475e-01],
       [  2.34311738e-03,   4.19568245e-02,   3.33800487e-01, ...,
          8.25387592e-02,   6.92307692e-02,   6.62251656e-02],
       [  5.22607063e-04,   4.79630919e-02,   3.34092457e-01, ...,
          6.01948726e-01,   1.26923077e-01,   8.83002208e-02]])

### *Robust scaler*

In [103]:
def robust_normalize(X):
    from sklearn.preprocessing import robust_scale
    X = robust_scale(X)
    return X
X_train,X_test = robust_normalize(X_train),minmax_scale(X_test)
X_train

array([[ 0.18203088,  0.17231284, -0.45333333, ..., -0.32504146,
        -0.39130435,  0.09375   ],
       [ 0.27187646, -0.14219992, -0.24      , ..., -0.19369818,
         1.26086957,  0.9375    ],
       [-1.06644829, -0.14889168,  0.58666667, ...,  0.01525705,
        -0.2173913 , -0.0625    ],
       ..., 
       [-1.06925597, -0.11375993,  3.21333333, ...,  0.20563847,
         0.        ,  0.125     ],
       [ 0.1043519 ,  0.32789628,  0.13333333, ..., -0.4358209 ,
        -0.30434783, -0.1875    ],
       [-0.24754328, -0.33960686, -0.34666667, ...,  2.15655058,
         0.26086957,  0.0625    ]])

### *Std-mean Scaler*

In [105]:
def st_scaler_sk(X):
    from sklearn.preprocessing import StandardScaler
    scaler = StandardScaler()
    X = scaler.fit(X).transform(X)
    # y_mean = scaler.fit(y_train).mean_
    # y_std = np.sqrt(scaler.var_)
    return X

X_train,X_test = st_scaler_sk(X_train),minmax_scale(X_test)
X_train

array([[-0.08758197, -0.1344008 , -0.00178728, ..., -0.21435405,
         0.13538382, -0.23239251],
       [-0.08980309, -0.6961429 , -0.06246092, ...,  1.05003978,
        -0.48204966,  0.43572106],
       [-0.03495859, -0.06884538, -0.02345644, ...,  0.3162232 ,
        -0.52063925, -0.59877738],
       ..., 
       [-0.03465105,  0.37421881,  0.02180802, ..., -0.49822031,
        -0.2891017 , -0.59877738],
       [-0.09260511, -0.57181366, -0.02634566, ..., -0.30129738,
        -0.40487048,  0.82365797],
       [-0.09759408, -1.55966597, -0.06920244, ..., -0.5658429 ,
        -1.09948314, -0.57722532]])

# Classication
### *(In the examples below, I used the std-mean scaler.)*

### *Random Forest*

In [115]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import precision_score
def rf_clf():
    clf = RandomForestClassifier(n_estimators=100, random_state=0)
    clf.fit(X_train, Y_train)
    y_pred = clf.predict(X_test)
    print("Random Forest Classifier performance\n", "=" * 20)
    print(f"Accuracy score: {clf.score(X_test, Y_test): .2f}")
    print(f"Precision score: {precision_score(Y_test, y_pred): .2f}")
    return y_pred
y_pred = rf_clf()
# y_pred

Random Forest Classifier performance
Accuracy score:  0.90
Precision score:  0.90


### *Guassian Naive Bayesian Classfier*

In [118]:
from sklearn.naive_bayes import GaussianNB
def GNB_clf():
    clf = GaussianNB()
    clf.fit(X_train, Y_train)
    y_pred = clf.predict(X_test)
    print("Guassian Naive Bayesian Classfier performance\n", "=" * 20)
    print(f"Accuracy score: {clf.score(X_test, Y_test): .2f}")
    print(f"Precision score: {precision_score(Y_test, y_pred): .2f}")
    return y_pred
y_pred = GNB_clf()

Guassian Naive Bayesian Classfier performance
Accuracy score:  0.78
Precision score:  0.83


### *Support Vector Machine Classifer*

In [119]:
from sklearn.svm import SVC
def SVM_clf():
    clf = SVC()
    clf.fit(X_train, Y_train)
    y_pred = clf.predict(X_test)
    print("Support Vector Machine Classifer performance\n", "=" * 20)
    print(f"Accuracy score: {clf.score(X_test, Y_test): .2f}")
    print(f"Precision score: {precision_score(Y_test, y_pred): .2f}")
    return y_pred
y_pred = SVM_clf()

Support Vector Machine Classifer performance
Accuracy score:  0.83
Precision score:  0.83


# Improvement Suggestions For Andy

### *First, I only select some features for the sake of simplicity. You can choose more or less features in the features  in the chose features sector.*
### *Second, I directly normalize the entire dataset, which is not a great idea. The thing is, the visual code from finding_donors, is specifically designed for that dataset, and changing it is beyond my ability. It would be great if you could do some feature engineering work for me (such as log some skewed distributed features, etc).*
### *Third, I only paired one of the three ways of normalization, which is the std-mean scaler ( for no good reasons), with each classifer. You could do some more pairing later.*
### *Fourth, it would be great if you could help with the extraxtion of importance features from these features. I have no idea how to do that because: the importance extraction in finding donors instance can be done easily since they train the dataframe but not the matrix. However, there will be a lot of mishaping bugs or other nonsense bullshit bugs if you train data in the dataframe directly, therefore, in this case, I trained the data in a numpy matrix.*
### *Little more in the future, ploting... this is a hard one, and is quite necessary for presentation. And I am having a little bit of trouble to draw fancy graphs...*